// winograd_conv_nchw_ref.cpp - ARCHIVED native-NCHW Winograd convolution
//
// !! DO NOT EDIT THIS FILE IN NORMAL DEVELOPMENT !!
//
// This is a frozen snapshot of the *original* `winograd_convolution` from
// before the 2026-08-11 layout refactor. It kept a native NCHW path: tile
// extraction and output write-back read/write channels with stride H*W / OH*OW
// (cache-line-wasteful on a no-L3 machine), while the compute
// (weight/input/output transforms, GEMM) was identical to the NHWC path.
//
// Why it's archived here:
//   The NCHW path in `src/winograd_conv.cpp` was re-implemented as a thin
//   wrapper: NCHW input is converted to NHWC, the (shared, faster) NHWC
//   compute kernel runs, then the output is converted back to NCHW. That
//   leaves exactly one compute kernel to maintain. This file preserves the
//   pre-refactor native-NCHW implementation as a *buildable reference* so it
//   can be (a) compared against the wrapper for numerical equivalence and
//   (b) re-benchmarked to judge whether the conversion-wrapper is actually a
//   net win for NCHW inputs on the target (see PERFORMANCE_ANALYSIS.md §12
//   and docs/why_faster_than_acl_23.11.md §4.6).
//
// Usage (see CMakeLists.txt, target `winograd_ref_test`):
//   - link this file against libwinograd_conv (it reuses dispatch_*,
//     winograd_gemm, copy_f32 from the library).
//   - call winograd_convolution_nchw_ref(...) exactly like the public API,
//     forcing NCHW layout.

#include "winograd_convolution.hpp"
#include "winograd_conv_nchw_ref.hpp"
#include <cstring>
#include <cmath>
#include <algorithm>
#include <cstdlib>
#include <arm_neon.h>

#if defined(__ARM_FEATURE_SVE)
#include "winograd_transforms_sve.hpp"
#endif
#if defined(__ARM_FEATURE_SME)
#include "winograd_transforms_sme.hpp"
#endif

#ifdef USE_OPENBLAS
#include <cblas.h>
extern "C" void openblas_set_num_threads(int);
#endif

namespace winograd_conv {

// ============================================================================
// Per-thread grow-on-demand scratch buffers (frozen copy from winograd_conv.cpp)
// ============================================================================
// Each logical buffer owns a thread_local allocation that grows to the max
// size ever needed and is reused across calls. malloc'd memory is never
// zeroed — every scratch is fully overwritten before being read by its caller.
// IMPORTANT: each logical buffer needs its OWN Scratch (aliasing bug).

namespace {

struct Scratch {
    float* ptr = nullptr;
    size_t cap = 0;
    ~Scratch() { free(ptr); }
};

inline float* scratch_f32(size_t n, Scratch& s) {
    if (s.cap < n) {
        free(s.ptr);
        s.ptr = static_cast<float*>(malloc(n * sizeof(float)));
        s.cap = n;
    }
    return s.ptr;
}

thread_local Scratch sU, sM, sV;
thread_local Scratch sd_tile, sU_tile, sM_tile, sf_tile, sg_wt, sV_oc_wt;

} // anonymous namespace

// ============================================================================
// ARCHIVED native-NCHW Winograd convolution (pre-2026-08-11)
// ============================================================================
// Verbatim copy of the historical `winograd_convolution`, including BOTH
// layout branches. The NHWC branch is vestigial here (the main library's NHWC
// kernel is identical); the NCHW branch is the preserved reference. Always
// pass Layout::NCHW.

void winograd_convolution_nchw_ref(
    const float* src,   // NCHW: [N][IC][IH][IW]
    const float* wei,   // [OC][IC][3][3]
    const float* bias,  // [OC] or nullptr
    float* dst,         // NCHW: [N][OC][OH][OW]
    int N, int IC, int IH, int IW,
    int OC, int OH, int OW,
    const WinogradConfig& config,
    float act_min, float act_max
) {
#ifdef USE_OPENBLAS
    openblas_set_num_threads(1);
#endif

    const int TS = config.input_tile_rows;
    const int OT = config.output_tile_rows;
    const int NM = config.n_multis;
    const bool is_f44 = (TS == 6);

    ISALevel isa = isa_level();
    if (const char* env = std::getenv("WINOGRAD_ISA")) {
        isa = parse_isa(env);
    }

    int n_tile_rows = config.n_tile_rows(OH);
    int n_tile_cols = config.n_tile_cols(OW);
    int n_tiles = n_tile_rows * n_tile_cols;

    int U_size = NM * n_tiles * IC;
    int M_size = NM * n_tiles * OC;
    int V_size = TS * TS * OC * IC;
    float* U = scratch_f32(U_size, sU);
    float* M_buf = scratch_f32(M_size, sM);
    float* V = scratch_f32(V_size, sV);

    #pragma omp parallel
    {
        float* d_tile = scratch_f32(TS * TS * IC, sd_tile);
        float* U_tile = scratch_f32(TS * TS * IC, sU_tile);
        float* M_tile = scratch_f32(TS * TS * OC, sM_tile);
        float* f_tile = scratch_f32(OT * OT * OC, sf_tile);
        float* g_wt = scratch_f32(9 * IC, sg_wt);
        float* V_oc_wt = scratch_f32(TS * TS * IC, sV_oc_wt);

        // ---- Step 1: Weight transform (parallelized over OC) ----
        #pragma omp for schedule(dynamic, 4)
        for (int oc = 0; oc < OC; oc++) {
            for (int ic = 0; ic < IC; ic++)
                for (int kh = 0; kh < 3; kh++)
                    for (int kw = 0; kw < 3; kw++)
                        g_wt[(kh * 3 + kw) * IC + ic] =
                            wei[((oc * IC + ic) * 3 + kh) * 3 + kw];
            dispatch_weight_transform(g_wt, V_oc_wt, IC, is_f44, isa);
            for (int m = 0; m < TS * TS; m++)
                for (int ic = 0; ic < IC; ic++)
                    V[m * OC * IC + oc * IC + ic] = V_oc_wt[m * IC + ic];
        }

        // ---- Step 2: Per-batch loop ----
        for (int n = 0; n < N; n++) {
            // Phase 1: Input transform
            #pragma omp for collapse(2) schedule(dynamic, 2)
            for (int tr = 0; tr < n_tile_rows; tr++) {
                for (int tc = 0; tc < n_tile_cols; tc++) {
                    int tile_idx = tr * n_tile_cols + tc;

                    bool is_edge = (tr == 0 || tr == n_tile_rows - 1 ||
                                    tc == 0 || tc == n_tile_cols - 1);
                    if (is_edge) {
                        memset(d_tile, 0, TS * TS * IC * sizeof(float));
                    }

                    int ih_begin = tr * OT - 1;
                    int ti_start = (ih_begin < 0) ? -ih_begin : 0;
                    int ti_end   = (ih_begin + TS > IH) ? (IH - ih_begin) : TS;
                    if (ti_end < ti_start) ti_end = ti_start;
                    int iw_begin = tc * OT - 1;
                    int tj_start = (iw_begin < 0) ? -iw_begin : 0;
                    int tj_end   = (iw_begin + TS > IW) ? (IW - iw_begin) : TS;
                    if (tj_end < tj_start) tj_end = tj_start;

                    for (int ti = ti_start; ti < ti_end; ti++) {
                        int ih = tr * OT - 1 + ti;
                        for (int tj = tj_start; tj < tj_end; tj++) {
                            int iw = tc * OT - 1 + tj;
                            // NCHW extract: channel-strided reads (the archived path)
                            for (int ic = 0; ic < IC; ic++)
                                d_tile[(ti * TS + tj) * IC + ic] =
                                    src[((n * IC + ic) * IH + ih) * IW + iw];
                        }
                    }

                    dispatch_input_transform(d_tile, U_tile, IC, is_f44, isa);

                    for (int ti = 0; ti < TS; ti++) {
                        for (int tj = 0; tj < TS; tj++) {
                            int ts_idx = ti * TS + tj;
                            copy_f32(U_tile + (ti * TS + tj) * IC,
                                     U + (ts_idx * n_tiles + tile_idx) * IC, IC);
                        }
                    }
                }
            }

            // Phase 2: GEMM
            #pragma omp for schedule(dynamic)
            for (int ts_idx = 0; ts_idx < NM; ts_idx++) {
                const float* U_slice = U + ts_idx * n_tiles * IC;
                const float* V_slice = V + ts_idx * OC * IC;
                float* M_slice = M_buf + ts_idx * n_tiles * OC;
                winograd_gemm(U_slice, V_slice, M_slice, n_tiles, OC, IC);
            }

            // Phase 3: Output transform
            #pragma omp for collapse(2) schedule(dynamic, 2) nowait
            for (int tr = 0; tr < n_tile_rows; tr++) {
                for (int tc = 0; tc < n_tile_cols; tc++) {
                    int tile_idx = tr * n_tile_cols + tc;

                    for (int ti = 0; ti < TS; ti++) {
                        for (int tj = 0; tj < TS; tj++) {
                            int ts_idx = ti * TS + tj;
                            copy_f32(M_buf + (ts_idx * n_tiles + tile_idx) * OC,
                                     M_tile + (ti * TS + tj) * OC, OC);
                        }
                    }

                    dispatch_output_transform(M_tile, f_tile, OC,
                                              bias, act_min, act_max, is_f44, isa);

                    for (int oi = 0; oi < OT; oi++) {
                        for (int oj = 0; oj < OT; oj++) {
                            int oh = tr * OT + oi;
                            int ow = tc * OT + oj;
                            if (oh < OH && ow < OW) {
                                // NCHW write-back: channel-strided writes (archived path)
                                for (int oc = 0; oc < OC; oc++) {
                                    dst[((n * OC + oc) * OH + oh) * OW + ow] =
                                        f_tile[(oi * OT + oj) * OC + oc];
                                }
                            }
                        }
                    }
                }
            }
        } // end for each batch
    } // end single parallel region
}

} // namespace winograd_conv
